name: Main
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Create files
      run: |
        echo $PWD
        ls -alF
        echo "Hello!" > ~/file1.txt
        echo "Howdy!" > ~/file2.txt
        ${{ github.workspace }}/myscript.sh

    - name: Verify
      run: |
        echo $PWD
        ls -alF
        cd ~
        echo $PWD
        ls -alF
        ${{ github.workspace }}/myscript.sh

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          ~/file1.txt
          ~/file2.txt


  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}

    - name: Verify
      run: |
        cd $GITHUB_WORKSPACE
        echo $PWD
        ls -alF
        cat file1.txt
        cat file2.txt
